//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 2016/05/14 5:28:08 PM
namespace ODataDemo.Models
{
    /// <summary>
    /// There are no comments for PersonSingle in the schema.
    /// </summary>
    public partial class PersonSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Person>
    {
        /// <summary>
        /// Initialize a new PersonSingle object.
        /// </summary>
        public PersonSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new PersonSingle object.
        /// </summary>
        public PersonSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new PersonSingle object.
        /// </summary>
        public PersonSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Person> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Devices in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::ODataDemo.Models.Device> Devices
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Devices == null))
                {
                    this._Devices = Context.CreateQuery<global::ODataDemo.Models.Device>(GetPath("Devices"));
                }
                return this._Devices;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::ODataDemo.Models.Device> _Devices;
        /// <summary>
        /// There are no comments for Friends in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::ODataDemo.Models.Person> Friends
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Friends == null))
                {
                    this._Friends = Context.CreateQuery<global::ODataDemo.Models.Person>(GetPath("Friends"));
                }
                return this._Friends;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::ODataDemo.Models.Person> _Friends;
    }
    /// <summary>
    /// There are no comments for Person in the schema.
    /// </summary>
    /// <KeyProperties>
    /// PersonID
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("PersonID")]
    public partial class Person : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Person object.
        /// </summary>
        /// <param name="personID">Initial value of PersonID.</param>
        /// <param name="name">Initial value of Name.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static Person CreatePerson(int personID, string name)
        {
            Person person = new Person();
            person.PersonID = personID;
            person.Name = name;
            return person;
        }
        /// <summary>
        /// There are no comments for Property PersonID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public int PersonID
        {
            get
            {
                return this._PersonID;
            }
            set
            {
                this.OnPersonIDChanging(value);
                this._PersonID = value;
                this.OnPersonIDChanged();
                this.OnPropertyChanged("PersonID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _PersonID;
        partial void OnPersonIDChanging(int value);
        partial void OnPersonIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Surname in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string Surname
        {
            get
            {
                return this._Surname;
            }
            set
            {
                this.OnSurnameChanging(value);
                this._Surname = value;
                this.OnSurnameChanged();
                this.OnPropertyChanged("Surname");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Surname;
        partial void OnSurnameChanging(string value);
        partial void OnSurnameChanged();
        /// <summary>
        /// There are no comments for Property Devices in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceCollection<global::ODataDemo.Models.Device> Devices
        {
            get
            {
                return this._Devices;
            }
            set
            {
                this.OnDevicesChanging(value);
                this._Devices = value;
                this.OnDevicesChanged();
                this.OnPropertyChanged("Devices");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::ODataDemo.Models.Device> _Devices = new global::Microsoft.OData.Client.DataServiceCollection<global::ODataDemo.Models.Device>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnDevicesChanging(global::Microsoft.OData.Client.DataServiceCollection<global::ODataDemo.Models.Device> value);
        partial void OnDevicesChanged();
        /// <summary>
        /// There are no comments for Property Friends in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceCollection<global::ODataDemo.Models.Person> Friends
        {
            get
            {
                return this._Friends;
            }
            set
            {
                this.OnFriendsChanging(value);
                this._Friends = value;
                this.OnFriendsChanged();
                this.OnPropertyChanged("Friends");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::ODataDemo.Models.Person> _Friends = new global::Microsoft.OData.Client.DataServiceCollection<global::ODataDemo.Models.Person>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnFriendsChanging(global::Microsoft.OData.Client.DataServiceCollection<global::ODataDemo.Models.Person> value);
        partial void OnFriendsChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for DeviceSingle in the schema.
    /// </summary>
    public partial class DeviceSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Device>
    {
        /// <summary>
        /// Initialize a new DeviceSingle object.
        /// </summary>
        public DeviceSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new DeviceSingle object.
        /// </summary>
        public DeviceSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new DeviceSingle object.
        /// </summary>
        public DeviceSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Device> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Person in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::ODataDemo.Models.PersonSingle Person
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Person == null))
                {
                    this._Person = new global::ODataDemo.Models.PersonSingle(this.Context, GetPath("Person"));
                }
                return this._Person;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::ODataDemo.Models.PersonSingle _Person;
    }
    /// <summary>
    /// There are no comments for Device in the schema.
    /// </summary>
    /// <KeyProperties>
    /// DeviceID
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("DeviceID")]
    public partial class Device : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Device object.
        /// </summary>
        /// <param name="deviceID">Initial value of DeviceID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static Device CreateDevice(int deviceID)
        {
            Device device = new Device();
            device.DeviceID = deviceID;
            return device;
        }
        /// <summary>
        /// There are no comments for Property DeviceID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public int DeviceID
        {
            get
            {
                return this._DeviceID;
            }
            set
            {
                this.OnDeviceIDChanging(value);
                this._DeviceID = value;
                this.OnDeviceIDChanged();
                this.OnPropertyChanged("DeviceID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _DeviceID;
        partial void OnDeviceIDChanging(int value);
        partial void OnDeviceIDChanged();
        /// <summary>
        /// There are no comments for Property DeviceDescription in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string DeviceDescription
        {
            get
            {
                return this._DeviceDescription;
            }
            set
            {
                this.OnDeviceDescriptionChanging(value);
                this._DeviceDescription = value;
                this.OnDeviceDescriptionChanged();
                this.OnPropertyChanged("DeviceDescription");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _DeviceDescription;
        partial void OnDeviceDescriptionChanging(string value);
        partial void OnDeviceDescriptionChanged();
        /// <summary>
        /// There are no comments for Property Person in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::ODataDemo.Models.Person Person
        {
            get
            {
                return this._Person;
            }
            set
            {
                this.OnPersonChanging(value);
                this._Person = value;
                this.OnPersonChanged();
                this.OnPropertyChanged("Person");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::ODataDemo.Models.Person _Person;
        partial void OnPersonChanging(global::ODataDemo.Models.Person value);
        partial void OnPersonChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::ODataDemo.Models.Person as global::ODataDemo.Models.PersonSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::ODataDemo.Models.PersonSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::ODataDemo.Models.Person> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::ODataDemo.Models.PersonSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::ODataDemo.Models.Person as global::ODataDemo.Models.PersonSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="personID">The value of personID</param>
        public static global::ODataDemo.Models.PersonSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::ODataDemo.Models.Person> source,
            int personID)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "PersonID", personID }
            };
            return new global::ODataDemo.Models.PersonSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::ODataDemo.Models.Device as global::ODataDemo.Models.DeviceSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::ODataDemo.Models.DeviceSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::ODataDemo.Models.Device> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::ODataDemo.Models.DeviceSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::ODataDemo.Models.Device as global::ODataDemo.Models.DeviceSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="deviceID">The value of deviceID</param>
        public static global::ODataDemo.Models.DeviceSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::ODataDemo.Models.Device> source,
            int deviceID)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "DeviceID", deviceID }
            };
            return new global::ODataDemo.Models.DeviceSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
    }
}
namespace OdataDemo
{
    /// <summary>
    /// There are no comments for OdataDemoContainer in the schema.
    /// </summary>
    public partial class OdataDemoContainer : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new OdataDemoContainer object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public OdataDemoContainer(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for People in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::ODataDemo.Models.Person> People
        {
            get
            {
                if ((this._People == null))
                {
                    this._People = base.CreateQuery<global::ODataDemo.Models.Person>("People");
                }
                return this._People;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::ODataDemo.Models.Person> _People;
        /// <summary>
        /// There are no comments for People in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToPeople(global::ODataDemo.Models.Person person)
        {
            base.AddObject("People", person);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private const string Edmx = @"<edmx:Edmx Version=""4.0"" xmlns:edmx=""http://docs.oasis-open.org/odata/ns/edmx"">
  <edmx:DataServices>
    <Schema Namespace=""ODataDemo.Models"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityType Name=""Person"">
        <Key>
          <PropertyRef Name=""PersonID"" />
        </Key>
        <Property Name=""PersonID"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Name"" Type=""Edm.String"" Nullable=""false"" />
        <Property Name=""Surname"" Type=""Edm.String"" />
        <NavigationProperty Name=""Devices"" Type=""Collection(ODataDemo.Models.Device)"" ContainsTarget=""true"" />
        <NavigationProperty Name=""Friends"" Type=""Collection(ODataDemo.Models.Person)"" />
      </EntityType>
      <EntityType Name=""Device"">
        <Key>
          <PropertyRef Name=""DeviceID"" />
        </Key>
        <Property Name=""DeviceID"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""DeviceDescription"" Type=""Edm.String"" />
        <NavigationProperty Name=""Person"" Type=""ODataDemo.Models.Person"" />
      </EntityType>
    </Schema>
    <Schema Namespace=""OdataDemo"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityContainer Name=""OdataDemoContainer"">
        <EntitySet Name=""People"" EntityType=""ODataDemo.Models.Person"">
          <NavigationPropertyBinding Path=""Friends"" Target=""People"" />
        </EntitySet>
      </EntityContainer>
    </Schema>
  </edmx:DataServices>
</edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader(Edmx);
                try
                {
                    return global::Microsoft.OData.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
}
